/* tslint:disable */
/* eslint-disable */
/**
 * demo
 * OpenAPIのサンプルプロジェクト
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Post
 */
export interface Post {
    /**
     * 記事のID
     * @type {number}
     * @memberof Post
     */
    id: number;
    /**
     * 記事タイトル
     * @type {Date}
     * @memberof Post
     */
    title?: Date;
    /**
     * 記事の内容
     * @type {string}
     * @memberof Post
     */
    content?: string;
}

export function PostFromJSON(json: any): Post {
    return PostFromJSONTyped(json, false);
}

export function PostFromJSONTyped(json: any, ignoreDiscriminator: boolean): Post {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': json['id'],
        'title': !exists(json, 'title') ? undefined : (new Date(json['title'])),
        'content': !exists(json, 'content') ? undefined : json['content'],
    };
}

export function PostToJSON(value?: Post | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'title': value.title === undefined ? undefined : (value.title.toISOString().substr(0,10)),
        'content': value.content,
    };
}


