=begin
demo

OpenAPIのサンプルプロジェクト

The version of the OpenAPI document: 1.0
Generated by: https://github.com/openapitools/openapi-generator.git

=end

class InitTables < ActiveRecord::Migration
  def change
    create_table "inline_object".pluralize.to_sym, id: false do |t|
      t.string :title
      t.string :content

      t.timestamps
    end

    create_table "post".pluralize.to_sym, id: false do |t|
      t.integer :id
      t.Date :title
      t.string :content

      t.timestamps
    end

  end
end
