=begin
demo

OpenAPIのサンプルプロジェクト

The version of the OpenAPI document: 1.0
Generated by: https://github.com/openapitools/openapi-generator.git

=end
class DefaultController < ApplicationController

  def get_posts
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def post
    # Your code here

    render json: {"message" => "yes, it worked"}
  end
end
