=begin
demo

OpenAPIのサンプルプロジェクト

The version of the OpenAPI document: 1.0
Generated by: https://github.com/openapitools/openapi-generator.git

=end
class DefaultController < ApplicationController

  def get_posts
    # Your code here

    render json: {
      id: 142,
      title: 'タイトル',
      content: '記事内容',
      hoge: 'hogehoge'
    }
  end

  def post
    # Your code here

    render json: {
      id: 142,
      title: 'タイトル',
      content: '記事内容'
    }
  end
end
