# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: proto/posts.proto for package 'Posts'

require 'grpc'
require 'proto/posts_pb'

module Posts
  module Posts
    class Service

      include GRPC::GenericService

      self.marshal_class_method = :encode
      self.unmarshal_class_method = :decode
      self.service_name = 'Posts.Posts'

      rpc :GetPosts, ::Google::Protobuf::Empty, ::Posts::GetPostsResponse
      rpc :AddPost, ::Posts::AddPostRequest, ::Posts::AddPostResponse
    end

    Stub = Service.rpc_stub_class
  end
end
