=begin
demo

OpenAPIのサンプルプロジェクト

The version of the OpenAPI document: 1.0
Generated by: https://github.com/openapitools/openapi-generator.git

=end


class InlineObject < ApplicationRecord
  validates_presence_of :title
  validates_presence_of :content

end
