/* tslint:disable */
/* eslint-disable */
/**
 * demo
 * OpenAPIのサンプルプロジェクト
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import {
    InlineObject,
    InlineObjectFromJSON,
    InlineObjectToJSON,
    Post,
    PostFromJSON,
    PostToJSON,
} from '../models';

export interface PostRequest {
    inlineObject?: InlineObject;
}

/**
 * 
 */
export class DefaultApi extends runtime.BaseAPI {

    /**
     * 記事一覧の取得
     * 記事一覧
     */
    async getPostsRaw(): Promise<runtime.ApiResponse<Post>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/posts`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        });

        return new runtime.JSONApiResponse(response, (jsonValue) => PostFromJSON(jsonValue));
    }

    /**
     * 記事一覧の取得
     * 記事一覧
     */
    async getPosts(): Promise<Post> {
        const response = await this.getPostsRaw();
        return await response.value();
    }

    /**
     * 記事の作成
     * 記事作成
     */
    async postRaw(requestParameters: PostRequest): Promise<runtime.ApiResponse<Array<Post>>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/post`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: InlineObjectToJSON(requestParameters.inlineObject),
        });

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(PostFromJSON));
    }

    /**
     * 記事の作成
     * 記事作成
     */
    async post(requestParameters: PostRequest): Promise<Array<Post>> {
        const response = await this.postRaw(requestParameters);
        return await response.value();
    }

}
